/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Usuario.java
 *
 * Created on 27-oct-2009, 12:57:47
 */

package sistema_nomina;
import java.awt.Image.*;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.util.*;
import java.util.logging.*;
import java.awt.*;
//import controlador.IngresarListener;
import java.awt.SplashScreen;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//import test.Sistema;
import java.sql.*;

import java.io.*;
/**
 *
 * @author Allen
 */
public class Usuario extends javax.swing.JFrame implements Runnable {
    private String usuario;
    private String clave;
    private boolean entrar= false;
    private Thread hilo;

    private Connection conn= null;
    private Statement stmt= null;
    PreparedStatement psc;




    /** Creates new form Usuario */

    public boolean isEntra(){
     return entrar;
    }// isEntra

    public Usuario() throws NullPointerException {
        initComponents();
        this.setIconImage (new ImageIcon(getClass().getResource("/imagenes/balanicon.png")).getImage());
       
        String tt="Ingrese Usuario y Contraseña";
        setTitle(tt);

         try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        // fuerza a cada componente de la ventana invocar el método updateUI
        } catch (InstantiationException e) {
        } catch (ClassNotFoundException e) {
        } catch (UnsupportedLookAndFeelException e) {
        } catch (IllegalAccessException e) {
        }
        this.setLocationRelativeTo(null);

        hilo = new Thread(this);

        this.setVisible(true);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClaveTex = new javax.swing.JPasswordField();
        UsuaTEx = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        AceptBoton = new javax.swing.JButton();
        CancelBoton = new javax.swing.JButton();
        Alerta = new javax.swing.JLabel();

        setIconImage(getIconImage());

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("1"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setText("Usuario: ");

        jLabel2.setText("   Clave:  ");

        ClaveTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveTexActionPerformed(evt);
            }
        });

        try {
            UsuaTEx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**********")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        UsuaTEx.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        AceptBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        AceptBoton.setText("Aceptar");
        AceptBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBotonActionPerformed(evt);
            }
        });

        CancelBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancel.png"))); // NOI18N
        CancelBoton.setText("Cancelar");
        CancelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AceptBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(CancelBoton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBoton)
                    .addComponent(AceptBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Alerta.setFont(new java.awt.Font("Tahoma", 1, 12));
        Alerta.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClaveTex, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsuaTEx)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Alerta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UsuaTEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ClaveTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Alerta, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClaveTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaveTexActionPerformed

    }//GEN-LAST:event_ClaveTexActionPerformed

    private void AceptBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBotonActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
                 conn = DriverManager.getConnection("jdbc:mysql://localhost/valandb","root","");
                 stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                 ResultSet result;

                 usuario= UsuaTEx.getText();
                 clave = ClaveTex.getText();

                 String sql="SELECT 'usuario', 'contraseña' FROM 'valandb'.'login';";
                    result =psc.executeQuery(sql);
                    while (result.next()) {
                    this.usuario=  result.getString("usuario");
                     this.clave=  result.getString("contraseña");
                        if (UsuaTEx.getText().equalsIgnoreCase(usuario) & ClaveTex.getText().equalsIgnoreCase(clave)) {
                            JOptionPane.showMessageDialog(null, "Acceso Autorizado");
                        } else {
                            this.Alerta.setText("Usuario o son Clave incorrectos.");
                        }

             }//fin while
         /*
            String c = new String(ClaveTex.getPassword());
            if(UsuaTEx.getText().equalsIgnoreCase(usuario)& c.equalsIgnoreCase(clave)){
               this.entrar=true;
               this.setVisible(false);
               hilo.start();
            }else{
                this.Alerta.setText("Usuario o son Clave incorrectos.");
                this.ClaveTex.setText("");
                this.UsuaTEx.setText("");*/

            }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }        catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
         

    }//GEN-LAST:event_AceptBotonActionPerformed

    private void CancelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBotonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(0);

    }//GEN-LAST:event_CancelBotonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
         ScreenSplash screenSplash = new ScreenSplash("/imagenes/balan_terminado.png");
         screenSplash.splash();

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Usuario us= new Usuario();
                us.setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptBoton;
    private javax.swing.JLabel Alerta;
    private javax.swing.JButton CancelBoton;
    private javax.swing.JPasswordField ClaveTex;
    private javax.swing.JFormattedTextField UsuaTEx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void run() {

        P_Principal p_Principal= null;
       
      /*  try {
            p_Principal = new P_Principal();
           
        //    P_PrincipalListener pp = new Panta_Prin(p_Principal);
         //   IngresarListener l = new IngresarListener(ingresar);
             //       ingresar.setVisible(true);
        } catch (UnsupportedLookAndFeelException ex) {
          //  Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }*/


    }//void run() 2

}
